---
- hosts: all
  connection: local
  tasks:
  
  - name: Install R packages
    shell: echo "install.packages(c('{{item|quote}}'),repos='http://cran.stat.ucla.edu/')"| R --no-save --no-restore-history
    args:
      creates: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/{{item}}
    with_items:
      - ggplot2
      - ggvis
      - knitr
      - plyr
      - dplyr
      - lubridate
      - zoo
      - forecast
      - sqldf
      - reshape2
