---
- hosts: all
  connection: local
  vars:
    app_name: Cornerstone
    app_name_pretty: Cornerstone
    app_url: "http://www.zennaware.com/mint/pepper/orderedlist/downloads/download.php?file=http%3A//www.zennaware.com/cornerstone/downloads/Cornerstone-2.7.11.zip"
    installer_type: app
    install_method: zip
    downloads: ~/.ansible-downloads/
    creates: /Applications/Cornerstone.app

  tasks:
    - include: ../install/{{ install_method }}.yml