---
- hosts: all
  connection: local
  vars:
    app_name: HandBrake
    app_name_pretty: HandBrake
    app_url: "http://handbrake.fr/rotation.php?file=HandBrake-0.9.9-MacOSX.6_GUI_x86_64.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/HandBrake-0.9.9-MacOSX.6_GUI_x86_64/
    downloads: ~/.ansible-downloads/
    creates: /Applications/HandBrake.app

  tasks:
    - include: ../install/{{ install_method }}.yml