---
- hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: Install Xcode CLI tools
      shell: /usr/bin/xcode-select --install creates=/usr/bin/gcc

    - name: Run Homebrew install script
      shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" creates=/usr/local/bin/brew
      register: brew_result
