---
- hosts: all
  connection: local
  vars:
    app_name: Knock
    app_name_pretty: Knock
    app_url: "http://knocktounlock.com/download"
    installer_type: app
    install_method: zip
    downloads: ~/.ansible-downloads/
    creates: /Applications/Knock.app

  tasks:
    - include: ../install/{{ install_method }}.yml