---
- hosts: all
  connection: local
  vars:
    app_name: nvALT
    app_name_pretty: nvALT
    app_url: "http://abyss.designheresy.com/nvaltb/nvalt2.2b106.zip"
    installer_type: app
    install_method: zip
    downloads: ~/.ansible-downloads/
    creates: /Applications/nvALT.app

  tasks:
    - include: ../install/{{ install_method }}.yml