---
- hosts: all
  connection: local
  gather_facts: False
  vars:
    app_name: RStudio
    app_name_pretty: RStudio
    app_url: "http://download1.rstudio.org/RStudio-0.98.1028.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/RStudio-0.98.1028/
    downloads: ~/.ansible-downloads/
    creates: /Applications/RStudio.app/

  tasks:
    - include: ../install/{{install_method}}.yml
