---
- hosts: all
  connection: local
  vars:
    app_name: Sequel\ Pro
    app_name_pretty: Sequel Pro
    app_url: "https://sequel-pro.googlecode.com/files/sequel-pro-1.0.2.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Sequel\ Pro\ 1.0.2/
    downloads: ~/.ansible-downloads/
    creates: /Applications/Sequel\ Pro.app

  tasks:
    - include: ../install/{{ install_method }}.yml