---
- hosts: all
  connection: local
  vars:
    app_name: Tower
    app_name_pretty: Tower
    app_url: "https://macapps.fournova.com/tower1-1060/download"
    installer_type: app
    install_method: zip
    downloads: ~/.ansible-downloads/
    creates: /Applications/Tower.app

  tasks:
    - include: ../install/{{ install_method }}.yml