---
- hosts: all
  connection: local
  vars:
    app_name: Transmit
    app_name_pretty: Transmit
    app_url: "http://download.panic.com/transmit/Transmit%204.4.6.zip"
    installer_type: app
    install_method: zip
    downloads: ~/.ansible-downloads/
    creates: /Applications/Transmit.app

  tasks:
    - include: ../install/{{ install_method }}.yml