---
- hosts: all
  connection: local
  gather_facts: False
  vars:
    app_name: VLC
    app_name_pretty: VLC
    app_version: 2.1.4
    app_url: "http://get.videolan.org/vlc/{{app_version}}/macosx/vlc-{{app_version}}.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/vlc-{{app_version}}/
    downloads: ~/.ansible-downloads/
    creates: /Applications/VLC.app

  tasks:
    - include: ../install/{{install_method}}.yml
